name: Build Game

on: push

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}

jobs:
  testRunner:
    name: Test in ${{ matrix.testMode }} ✨
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testMode:
          - EditMode
          - PlayMode
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Restore Library cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-test-project-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-test-project-
            Library-

      - name: Run tests
        uses: game-ci/unity-test-runner@v2
        id: testRunner
        with:
          testMode: ${{ matrix.testMode }}
          checkName: ${{ matrix.testMode }} test results
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v2
        with:
          name: Test results (${{ matrix.testMode }})
          path: ${{ steps.testRunner.outputs.artifactsPath }}

  buildWindows:
    needs: testRunner
    name: Build for Windows 🖥️
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Restore Library cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-build-StandaloneWindows64
          restore-keys: |
            Library-build-
            Library-

      - name: Build project for Windows
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 2022.3.19f1
          targetPlatform: StandaloneWindows64
          buildName: WindowsBuild
          buildPath: build/windows

      - name: Upload Windows build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: WindowsBuild
          path: build/windows

  buildMac:
    needs: testRunner
    name: Build for macOS 🍏
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Restore Library cache
        uses: actions/cache@v2
        with:
          path: Library
          key: Library-build-StandaloneOSX
          restore-keys: |
            Library-build-
            Library-

      - name: Build project for macOS
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 2022.3.19f1
          targetPlatform: StandaloneOSX
          buildName: MacBuild
          buildPath: build/mac

      - name: Upload macOS build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: MacBuild
          path: build/mac