name: Unity CI

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Unity
      uses: game-ci/unity-setup@v2
      with:
        unityVersion: 2022.3.19f1  # Specify your Unity version here

    - name: Build Windows
      uses: game-ci/unity-builder@v2
      with:
        projectPath: .
        targetPlatform: StandaloneWindows64
        buildName: WindowsBuild
        buildPath: build/windows

    - name: Upload Windows build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: WindowsBuild
        path: build/windows

  build-mac:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Unity
      uses: game-ci/unity-setup@v2
      with:
        unityVersion: 2022.3.19f1  # Specify your Unity version here

    - name: Build Mac
      uses: game-ci/unity-builder@v2
      with:
        projectPath: .
        targetPlatform: StandaloneOSX
        buildName: MacBuild
        buildPath: build/mac

    - name: Upload Mac build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: MacBuild
        path: build/mac